openapi: 3.0.4
info:
  title: Website Screenshot
  description: Web Screenshots is a simple tool for capturing screenshots of web pages. It returns an image screenshot of the web page provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/webscreenshots:
    post:
      summary: Capture Screenshot
      description: Web Screenshots is a simple tool for capturing screenshots of web pages. It returns an image screenshot of the web page provided.
      operationId: webscreenshots
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  width: 1024
                  height: 600
                  scaleFactor: 1
                  imageName: 78bdb087-756b-4107-83e1-82fd40171ed1.png
                  expires: 1725356395837
                  url: https://ebay.com/
                  downloadURL: https://storage.googleapis.com/apiverve-helpers.appspot.com/webscreenshots/78bdb087-756b-4107-83e1-82fd40171ed1.png?GoogleAccessId=1089020767582-compute%40developer.gserviceaccount.com&Expires=1725356395&Signature=jqAuoBhrbsSqs61blsFdnXEU35QOanhFnL0FN2d82cDDTXAUWonuRURUjyyhmABe02dVD3sMpvQDh0V39ROFcukPFASdIhr4HdWnKl743JLx03jrW%2FJ2baK3lZCZemPkS%2F61VqcHV1YB5XsxqsDNNkQ8QL8xlzUslHUgjuVKsorDCpBL5iFPSLo0l5DO3wvZ6UudJJP11j1MAnRmWQC7%2FkUBc7AP4akQvm6N7lftFkx8z6%2FptdxBt60w1XR6Ixoy6Vl31tvd6UjyWhjmF8JbujRSRYXmh0vjTNZBp5BX7xUntQUSMXhQf%2Bj3bXq7ZcsfMAAtqonqbzC6SBZgzSu2kA%3D%3D
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL of the web page to capture the screenshot (e.g., https://example.com)
                  example: https://ebay.com/
                type:
                  type: string
                  description: The type of the screenshot (png, jpeg, or webp)
                  default: jpg
                  example: png
                width:
                  type: integer
                  description: The width of the screenshot in pixels (e.g., 1920). Must be between 100 and 3840
                  default: '1920'
                  example: 1024
                height:
                  type: integer
                  description: The height of the screenshot in pixels (e.g., 1080).  Must be between 100 and 3840
                  default: '1080'
                  example: 600
                fullpage:
                  type: boolean
                  description: Whether to capture the full page screenshot (true or false)
                  default: false
                  example: false
              required:
              - url
              example:
                url: https://ebay.com/
                type: png
                width: 1024
                height: 600
                fullpage: false
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
