openapi: 3.0.4
info:
  title: Website Screenshot
  description: >-
    Web Screenshots is a simple tool for capturing screenshots of web pages. It
    returns an image screenshot of the web page provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/webscreenshots:
    post:
      summary: Capture Screenshot
      description: Capture a screenshot of a web page
      operationId: webscreenshots
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  width: 1024
                  height: 600
                  scaleFactor: 1
                  imageName: 77072426-6af8-45c2-93dd-d7013d2c765e.png
                  expires: 1766097105719
                  url: https://ebay.com/
                  downloadURL: >-
                    https://storage.googleapis.com/apiverve-helpers.appspot.com/webscreenshots/77072426-6af8-45c2-93dd-d7013d2c765e.png?GoogleAccessId=1089020767582-compute%40developer.gserviceaccount.com&Expires=1766097105&Signature=uZKa777XpeVnlwOZG7Uhjs%2BNkPzkEuiV4Wug2%2B%2BAHcPovRZ3iVjZEX%2FZhp7gnADXI6au5q0ggPwweoOFJeMCdk9zod6aZo4hlUDe1DsJf0oao4rh3tGUl5wPeudXLp7Y%2F3zVflup9Mp255LY6%2B2JdU0auOHdPnEYLDCvf705X9C%2BflmWQZKh7QKi74gvU8pqsP6Zc7SfJJsv5kmhP8SkO7TBZKBU6pAr2mNHKpKgB5mtfCRLbyPYcxawSGlTuyIyRXffWbkfHdDl6pquPX9J%2Fp5uGYM4jTrqrrrR1MPAOfkD7d9V5juqe5A7VvWmhiAyCMGDO%2BeqUO%2BSe6t9php0vA%3D%3D
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: >-
                    The URL of the web page to capture the screenshot (e.g.,
                    https://example.com)
                type:
                  type: string
                  description: The image format for the screenshot
                width:
                  type: number
                  description: >-
                    The width of the screenshot in pixels (e.g., 1920). Must be
                    between 100 and 3840
                height:
                  type: number
                  description: >-
                    The height of the screenshot in pixels (e.g., 1080).  Must
                    be between 100 and 3840
                fullpage:
                  type: boolean
                  description: Whether to capture the full page screenshot (true or false)
              required:
                - url
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  url: https://ebay.com/
  type: png
  width: 1024
  height: 600
  fullpage: false
